### ISSUE TITLE
Travis CI set up

### ISSUE THREAD

**Issue by marcin-wosinek** [Altruisto/altruisto#4]
TravisCI is great CI; and free for open source project. On eapoland/landing-page we use it for building github page:
https://travis-ci.org/eapoland/landing-page

and can be used to check all incoming commits with `lint` (at first) and with unit tests; e2e etc later on. 

The config itself can be added in PR; but travis needs as well access token for getting access to the repo itself:
https://docs.travis-ci.com/user/getting-started/

**Comment by marcin-wosinek** [comment]
The example of travis in action:
https://travis-ci.org/marcin-wosinek/altruisto

**Comment by kovsky0** [comment]
We're using heroku now :) There are some issues with deploying from monorepo but it's good enough for now.
