### ISSUE TITLE
The google chrome webstore link isn't working

### ISSUE THREAD

**Issue by davidfurlong** [Altruisto/altruisto#7]
<img width="1185" alt="Screenshot 2019-11-19 at 10 55 42" src="https://user-images.githubusercontent.com/614768/69136453-2c807680-0abb-11ea-8b7e-3344f1b154ca.png">

The indexed url on google search also 404s

**Comment by kovsky0** [comment]
Solved - the old chrome extension is unavailable, so I have added a signup form to be informed when new version is ready.

Thank you for submitting the issue :)
